Remove all DEVEL refs
hazelcast/homebrew-hz pull request #38
Opened 2024-08-15 11:17 UTC by nishaatr

2024-08-15 12:15 UTC, JackPGreen requested changes
Because these files are dynamically generated, I think any modification should wait until the generator (i.e. https://github.com/hazelcast/hazelcast-packaging/pull/224) is updated.
Otherwise an intermediate build will cause conflicts.

2024-08-15 12:55 UTC, nishaatr commented
> Because these files are dynamically generated, I think any modification should wait until the generator (i.e. [hazelcast/hazelcast-packaging#224](https://github.com/hazelcast/hazelcast-packaging/pull/224)) is updated. Otherwise an intermediate build will cause conflicts.

Makes sense. thanks

2024-08-16 08:33 UTC, ldziedziul approved these changes
> Remove all DEVEL refs as we don't package DEVEL - only produce Docker image See JIRA for more details
> 
> Not sure about the below as url is pointing to JFrog `devel` repo. **I think we can delete but do confirm?**

DR means devel release, it was a previous name, we can delete them as well

2024-08-16 08:35 UTC, nishaatr commented
> > Remove all DEVEL refs as we don't package DEVEL - only produce Docker image See JIRA for more details
> > Not sure about the below as url is pointing to JFrog `devel` repo. **I think we can delete but do confirm?**
> 
> DR means devel release, it was a previous name, we can delete them as well

Ah. should have been obvious. Normally DR means disaster recovery!
I will remove them soon. thanks

2024-08-16 09:33 UTC, ldziedziul commented
It's good that you haven't removed anything you wasn't sure 💪

2024-08-16 09:49 UTC, nishaatr commented
> It's good that you haven't removed anything you wasn't sure 💪

thanks. What can I say, I am risk averse. In my nature + I think I have learnt the hard way :slightly_smiling_face:

2024-08-16 10:31 UTC, JackPGreen requested changes

2024-08-16 10:31 UTC, JackPGreen commented on hazelcast-enterprise@5.1.dr6.rb
You've deleted this file, but the other files still contain a `conflicts_with` entry referencing it, leading to a warning.

2024-08-16 10:39 UTC, nishaatr commented on hazelcast-enterprise@5.1.dr6.rb
Opppss. Let me fix that . thanks

2024-08-16 10:48 UTC, nishaatr commented on hazelcast-enterprise@5.1.dr6.rb
Fixed [5e3926](https://github.com/hazelcast/homebrew-hz/pull/38/commits/5e3926945cc13d07395cedd7ed117eafab5fee6d)

Good catch. thanks

2024-08-16 10:50 UTC, JackPGreen approved these changes

2024-08-16 10:52 UTC, merged